name: immutable
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
 path: ^1.7.0
 meta:

 dartz:
 http: any
 freezed_annotation: any
 json_annotation:


dev_dependencies:
  pedantic: ^1.9.0
  json_serializable:
  freezed: any
  build_runner: any
  
