name: boilerplate_server_side_dart
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  envify: ^1.0.6
  mongo_dart: ^0.4.4
  shelf: ^0.7.5
  shelf_helpers: ^1.0.0-alpha.1
  shelf_router: ^0.7.4
  shelf_static: ^0.2.9+2
  crypto: ^2.1.5
  dart_jsonwebtoken: ^1.6.2

dev_dependencies:
  pedantic: ^1.9.0
  envify_generator: any
  build_runner: any
